spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 4
        one-indexed-parameters: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  servlet:
    encoding:
      force: true