package com.maybezone.productservice.domain.product.productenum;

public enum MainCategory {

    ACCESSORIES, APPLIANCES, BAGS_AND_LUGGAGE, BEAUTY_AND_HEALTH, CAR_AND_MOTORBIKE,
    GROCERY_AND_GOURMET_FOODS, HOME_AND_KITCHEN, HOME_KITCHEN_PETS, INDUSTRIAL_SUPPLIES, KIDS_FASHION,
    MENS_CLOTHING, MENS_SHOES, MUSIC, PET_SUPPLIES, SPORTS_AND_FITNESS,
    STORES, TOYS_AND_BABY_PRODUCTS, TV_AUDIO_CAMERAS, WOMENS_CLOTHING, WOMENS_SHOES

}
