package com.maybezone.productservice.domain.product.productenum;

public enum SubCategory {

    BAGS_AND_LUGGAGE, FASHION_AND_SILVER_JEWELLERY, GOLD_AND_DIAMOND_JEWELLERY, HANDBAGS_AND_CLUTCHES, JEWELLERY,
    SUNGLASSES, WATCHES, AIR_CONDITIONERS, ALL_APPLIANCES, HEATING_AND_COOLING_APPLIANCES,
    KITCHEN_AND_HOME_APPLIANCES, REFRIGERATORS, WASHING_MACHINES, BACKPACKS, RUCKSACKS,
    SUITCASES_AND_TROLLEY_BAGS, TRAVEL_ACCESSORIES, TRAVEL_DUFFLES, WALLETS, BEAUTY_AND_GROOMING,
    DIET_AND_NUTRITION, HEALTH_AND_PERSONAL_CARE, HOUSEHOLD_SUPPLIES, LUXURY_BEAUTY, MAKEUP,
    PERSONAL_CARE_APPLIANCES, VALUE_BAZAAR, ALL_CAR_AND_MOTORBIKE_PRODUCTS, CAR_AND_BIKE_CARE, CAR_ACCESSORIES,
    CAR_ELECTRONICS, CAR_PARTS, MOTORBIKE_ACCESSORIES_AND_PARTS, ALL_GROCERY_AND_GOURMET_FOODS, COFFEE_TEA_AND_BEVERAGES,
    SNACK_FOODS, ALL_HOME_AND_KITCHEN, BEDROOM_LINEN, FURNITURE, GARDEN_AND_OUTDOORS,
    HOME_DECOR, HOME_FURNISHING, HOME_IMPROVEMENT, HOME_STORAGE, INDOOR_LIGHTING,
    KITCHEN_AND_DINING, KITCHEN_STORAGE_AND_CONTAINERS, SEWING_AND_CRAFT_SUPPLIES, REFURBISHED_AND_OPEN_BOX, INDUSTRIAL_AND_SCIENTIFIC_SUPPLIES,
    JANITORIAL_AND_SANITATION_SUPPLIES, LAB_AND_SCIENTIFIC, TEST_MEASURE_AND_INSPECT, BABY_FASHION, KIDS_CLOTHING,
    KIDS_FASHION, KIDS_SHOES, KIDS_WATCHES, SCHOOL_BAGS, INNERWEAR,
    JEANS, SHIRTS, T_SHIRTS_AND_POLOS, CASUAL_SHOES, FORMAL_SHOES,
    SPORTS_SHOES, MUSICAL_INSTRUMENTS_AND_PROFESSIONAL_AUDIO, ALL_PET_SUPPLIES, DOG_SUPPLIES, ALL_EXERCISE_AND_FITNESS,
    ALL_SPORTS_FITNESS_AND_OUTDOORS, BADMINTON, CAMPING_AND_HIKING, CARDIO_EQUIPMENT, CRICKET,
    CYCLING, FITNESS_ACCESSORIES, FOOTBALL, RUNNING, STRENGTH_TRAINING,
    YOGA, AMAZON_FASHION, FASHION_SALES_AND_DEALS, MENS_FASHION, SPORTSWEAR,
    THE_DESIGNER_BOUTIQUE, WOMENS_FASHION, BABY_BATH_SKIN_AND_GROOMING, BABY_PRODUCTS, DIAPERS,
    INTERNATIONAL_TOY_STORE, NURSING_AND_FEEDING, STEM_TOYS_STORE, STROLLERS_AND_PRAMS, TOYS_AND_GAMES,
    TOYS_GIFTING_STORE, ALL_ELECTRONICS, CAMERA_ACCESSORIES, CAMERAS, HEADPHONES,
    HOME_AUDIO_AND_THEATER, HOME_ENTERTAINMENT_SYSTEMS, SECURITY_CAMERAS, SPEAKERS, TELEVISIONS,
    CLOTHING, ETHNIC_WEAR, LINGERIE_AND_NIGHTWEAR, WESTERN_WEAR, BALLERINAS,
    FASHION_SANDALS, SHOES

}
